sudo: false
language: php
php:
  - 7.2
  - 7.3
  - 7.4

before_script:
  - phpenv config-rm xdebug.ini
  - phpenv rehash
  - composer install

script:
  - vendor/bin/phing startup phpunitfast phpcs-console php-cs-fixer-dryrun
